server:
  port: 8898
spring:
  cloud:
    gateway:
      routes:
        - id: students-service
          uri: lb://students-service
          predicates:
            - Path=/students/**
        #- id: cursos-service
          #uri: lb://CURSOS-SERVICE
          #predicates:
          #  - Path=/cursos/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/