server:
  port: 8898

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: students-service
          uri: lb://students-service
          predicates:
            - Path=/students/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/